// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication2.Data.Context;

#nullable disable

namespace APIFruitFinalLeVraiFinalV2.Migrations
{
    [DbContext(typeof(FruitContext))]
    partial class FruitContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplication2.Models.Fruit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Couleur")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Origine")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Fruit", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 4,
                            Couleur = "Jaune",
                            Nom = "Banane",
                            Origine = "Amérique du sud"
                        },
                        new
                        {
                            Id = 5,
                            Couleur = "Vert",
                            Nom = "Raisin",
                            Origine = "Québec"
                        },
                        new
                        {
                            Id = 6,
                            Couleur = "Rouge",
                            Nom = "Fraise",
                            Origine = "Californie"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
